name: curtail
base: core22
adopt-info: curtail
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

slots:
  curtail:
    interface: dbus
    bus: session
    name: com.github.huluti.Curtail

apps:
  curtail:
    command: usr/bin/curtail
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
      - network-status
      - optical-drive
      - removable-media
    common-id: com.github.huluti.Curtail
    desktop: usr/share/applications/com.github.huluti.Curtail.desktop

parts:
  curtail:
    source: https://github.com/Huluti/Curtail.git
    source-tag: 1.7.0
    plugin: meson
    parse-info: [usr/share/metainfo/com.github.huluti.Curtail.appdata.xml]
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
      sed -e 's|Icon=com.github.huluti.Curtail|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/com.github.huluti.Curtail.svg|' -i data/com.github.huluti.Curtail.desktop.in

  oxipng:
    source: https://github.com/shssoichiro/oxipng.git
    source-tag: v8.0.0
    after: [curtail]
    plugin: rust
    build-packages:
      - cargo

  deps:
    after: [oxipng]
    plugin: nil
    stage-packages:
      - pngquant
      - scour
      - jpegoptim
      - libwebp7
    prime:
      - usr/lib/*/libjpeg.so*
      - usr/lib/*/libgomp.so*
      - usr/lib/*/libwebp.so*
      - usr/lib/*/libimagequant.so*
      - usr/lib/python3
      - usr/bin

  cleanup:
    after:
      - deps
    plugin: nil
    build-snaps:
      - gnome-42-2204
      - core22
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "core22" "gtk-common-themes"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done
